language: shell
arch:
  - amd64
  - arm64
os: linux

env:
  global:
    - ZIG_DIR=$HOME/zig
  
jobs:
  fast_finish: true

before_install:
  - cd /tmp
  - URL=$(wget -O - https://ziglang.org/download/index.json | jq -r '.master."'$(arch)'-linux".tarball' 2>&1)
  - wget $URL
  - tar xf $(basename $url)
  - mkdir "$ZIG_DIR"
  - mv $(basename -s .tar.xz $url)/* "$ZIG_DIR"/
  - cd -
  - export PATH=$PATH:$ZIG_DIR

addons:
  apt:
    update: true
    packages:
    - jq


script:
  - ls "$ZIG_DIR"
  - zig build test
  - zig build bench
  - zig fmt --check **.zig
