language: shell
arch:
  - amd64
  - arm64
os: linux

env:
  global:
    - ZIG_DIR=$HOME/zig
  
jobs:
  fast_finish: true

before_install:
  - ./install_zig.sh
  - export PATH=$PATH:$ZIG_DIR

addons:
  apt:
    update: true
    packages:
    - jq


script:
  - zig build test
  - zig build bench
  - zig fmt --check **.zig
